
package dk.skat.begrebsmodel._2009._01._15;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EORIVirksomhedSamlingHentService", targetNamespace = "http://skat.dk/begrebsmodel/2009/01/15/", wsdlLocation = "http://sktudv01esb01:8011/EORIS/EORIVirksomhedSamlingHentService?wsdl")
@HandlerChain(file = "EORIVirksomhedSamlingHentService_handler.xml")
public class EORIVirksomhedSamlingHentService
    extends Service
{

    private final static URL EORIVIRKSOMHEDSAMLINGHENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EORIVIRKSOMHEDSAMLINGHENTSERVICE_EXCEPTION;
    private final static QName EORIVIRKSOMHEDSAMLINGHENTSERVICE_QNAME = new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedSamlingHentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sktudv01esb01:8011/EORIS/EORIVirksomhedSamlingHentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EORIVIRKSOMHEDSAMLINGHENTSERVICE_WSDL_LOCATION = url;
        EORIVIRKSOMHEDSAMLINGHENTSERVICE_EXCEPTION = e;
    }

    public EORIVirksomhedSamlingHentService() {
        super(__getWsdlLocation(), EORIVIRKSOMHEDSAMLINGHENTSERVICE_QNAME);
    }

    public EORIVirksomhedSamlingHentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EORIVIRKSOMHEDSAMLINGHENTSERVICE_QNAME, features);
    }

    public EORIVirksomhedSamlingHentService(URL wsdlLocation) {
        super(wsdlLocation, EORIVIRKSOMHEDSAMLINGHENTSERVICE_QNAME);
    }

    public EORIVirksomhedSamlingHentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EORIVIRKSOMHEDSAMLINGHENTSERVICE_QNAME, features);
    }

    public EORIVirksomhedSamlingHentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EORIVirksomhedSamlingHentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EORIVirksomhedSamlingHentServicePortType
     */
    @WebEndpoint(name = "EORIVirksomhedSamlingHentServicePortType")
    public EORIVirksomhedSamlingHentServicePortType getEORIVirksomhedSamlingHentServicePortType() {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedSamlingHentServicePortType"), EORIVirksomhedSamlingHentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EORIVirksomhedSamlingHentServicePortType
     */
    @WebEndpoint(name = "EORIVirksomhedSamlingHentServicePortType")
    public EORIVirksomhedSamlingHentServicePortType getEORIVirksomhedSamlingHentServicePortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedSamlingHentServicePortType"), EORIVirksomhedSamlingHentServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EORIVIRKSOMHEDSAMLINGHENTSERVICE_EXCEPTION!= null) {
            throw EORIVIRKSOMHEDSAMLINGHENTSERVICE_EXCEPTION;
        }
        return EORIVIRKSOMHEDSAMLINGHENTSERVICE_WSDL_LOCATION;
    }

}
