
package dk.skat.eori.begrebsmodel._2009._01._15;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EORIVirksomhedValiderService", targetNamespace = "http://skat.dk/begrebsmodel/2009/01/15/", wsdlLocation = "http://sktudv01esb01:8011/intelligentstub/EORI/EORIVirksomhedValiderService?wsdl")
public class EORIVirksomhedValiderService
    extends Service
{

    private final static URL EORIVIRKSOMHEDVALIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EORIVIRKSOMHEDVALIDERSERVICE_EXCEPTION;
    private final static QName EORIVIRKSOMHEDVALIDERSERVICE_QNAME = new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedValiderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sktudv01esb01:8011/intelligentstub/EORI/EORIVirksomhedValiderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EORIVIRKSOMHEDVALIDERSERVICE_WSDL_LOCATION = url;
        EORIVIRKSOMHEDVALIDERSERVICE_EXCEPTION = e;
    }

    public EORIVirksomhedValiderService() {
        super(__getWsdlLocation(), EORIVIRKSOMHEDVALIDERSERVICE_QNAME);
    }

    public EORIVirksomhedValiderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EORIVIRKSOMHEDVALIDERSERVICE_QNAME, features);
    }

    public EORIVirksomhedValiderService(URL wsdlLocation) {
        super(wsdlLocation, EORIVIRKSOMHEDVALIDERSERVICE_QNAME);
    }

    public EORIVirksomhedValiderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EORIVIRKSOMHEDVALIDERSERVICE_QNAME, features);
    }

    public EORIVirksomhedValiderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EORIVirksomhedValiderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EORIVirksomhedValiderServicePortType
     */
    @WebEndpoint(name = "EORIVirksomhedValiderServicePortType")
    public EORIVirksomhedValiderServicePortType getEORIVirksomhedValiderServicePortType() {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedValiderServicePortType"), EORIVirksomhedValiderServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EORIVirksomhedValiderServicePortType
     */
    @WebEndpoint(name = "EORIVirksomhedValiderServicePortType")
    public EORIVirksomhedValiderServicePortType getEORIVirksomhedValiderServicePortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "EORIVirksomhedValiderServicePortType"), EORIVirksomhedValiderServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EORIVIRKSOMHEDVALIDERSERVICE_EXCEPTION!= null) {
            throw EORIVIRKSOMHEDVALIDERSERVICE_EXCEPTION;
        }
        return EORIVIRKSOMHEDVALIDERSERVICE_WSDL_LOCATION;
    }

}
